{
  "partyType": "Individual",
  "personName": "Muriel Satterfield III",
  "id": null,
  "nameSuffix": "Dr.",
  "currentEmployerName": "Smith, Abernathy and Pfeffer",
  "doForgetMeFromUpdateDate": "2017-10-09",
  "deathDate": "2017-10-09",
  "doExtractMyDataUpdateDate": "1964-04-13",
  "birthPlace": "West Arthurmouth",
  "isHighRiskOccupation": false,
  "doNotProcessReason": "nostrud",
  "yearlyIncomeRange": "2000000",
  "isTobaccoConsume": false,
  "residenceCaptureMethod": "culpa",
  "majorCitationCount": 830,
  "yearlyIncome": 310634,
  "doNotMarketFromUpdateDate": "1993-08-11",
  "middleName": "Gutkowski",
  "gender": "male",
  "convictionsCount": 53,
  "mothersMaidenName": "Weissnat",
  "occupationType": "official",
  "primaryHousehold": [
    "nulla",
    "ipsum"
  ],
  "auditInfo": {
    "createdDate": "2021-11-16T21:40:06.000Z",
    "createdBy": "Ken",
    "updatedDate": "2021-11-16T21:40:06.000Z",
    "updatedBy": "Ken",
    "isDeleted": false
  },
  "dependentCount": 216,
  "hospitalizationsLast5YearsCount": 724001,
  "hasAlcoholAbuseHistory": false,
  "personLifeStage": "Adult",
  "employedSinceDate": "1961-07-03",
  "isGoodStudent": true,
  "religion": "None",
  "occupation": "Developer",
  "globalParty": "3f337f22-7211-11eb-a776-0e41569acf90",
  "hasDrugAbuseHistory": false,
  "sendIndividualData": true,
  "birthDate": "1994-01-16",
  "surgeriesLast5YearsCount": 52,
  "doNotProfileFromUpdateDate": "1989-03-04",
  "mainPersonalityType": "Active",
  "mainDisabilityType": "None",
  "doNotTrackUpdateDate": "1960-11-01",
  "netWorth": 1611975,
  "primaryHobby": "fishing",
  "personHeight": 96,
  "salutation": "Mr.",
  "shouldForget": true,
  "maritalStatus": "Single",
  "mainPersonalValueType": "Rich",
  "ethnicity": "American",
  "militaryService": "None",
  "mainLifeStyleType": "Lavish",
  "doNotTrackLocationUpdateDate": "1988-05-29",
  "mailingName": "rest",
  "residenceCountryName": "USA",
  "militaryStatus": "Retired",
  "consumerCreditScoreProviderName": "Experian",
  "deathPlace": "",
  "doNotProcessFromUpdateDate": "1949-01-15",
  "firstName": "Kaleb",
  "highestEducationLevel": "Bachelors of Sciences",
  "isAlcoholConsumer": true,
  "officialName": "Jenks",
  "webSiteURL": "marlene.name",
  "mainLifeAttitudeType": "high",
  "childrenCount": 2,
  "mainDietaryHabitType": "Protein",
  "noMergeReason": "et",
  "weddingAnniversaryDate": "1944-12-10",
  "preferredName": "Koepp",
  "taxBracketRange": "22%",
  "secondLastName": "",
  "personWeight": 148,
  "personWeightUnitOfMeasure": "lbs",
  "orderingName": "dolore",
  "influencerRating": 47065285,
  "lastName": "Sanford",
  "consumerCreditScore": 73548089
}