/* Contact Point Type Entries */
insert into CONTACT_POINT_TYPE (ID, NAME, OPT_IN_PRIORITY, CREATED_BY, UPDATED_BY) values ( UUID(), "ContactPointAddress", 0, USER(), USER());
insert into CONTACT_POINT_TYPE (ID, NAME, OPT_IN_PRIORITY, CREATED_BY, UPDATED_BY) values ( UUID(), "ContactPointEmail", 0, USER(), USER());
insert into CONTACT_POINT_TYPE (ID, NAME, OPT_IN_PRIORITY, CREATED_BY, UPDATED_BY) values ( UUID(), "ContactPointPhone", 0, USER(), USER());

/** External ID Type Entries */
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "CORE_BANKING", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "CREDIT_CARD", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "DOCUSIGN", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "FIS", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "HOGAN", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "JIRA", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "LOS", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "MDM", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "OFBIZ", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_B2C", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_CORE", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_FSC_BANKING", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_FSC_INSURANCE", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_FSC_WEALTH", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SALESFORCE_MARKETING", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SAP_4HANA", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SAP_ECC", USER(), USER());
insert into EXTERNAL_ID_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values ( UUID(), "SERVICENOW", USER(), USER());

/* Party Relationship Type Entries */
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "AGENT", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "BUYER", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "CHILD", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "CLIENT", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "OTHER", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "RELATION", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "SPONSOR", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "SPOUSE", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "SUPPLIER", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "USER", USER(), USER());
insert into PARTY_RELATIONSHIP_TYPE (ID, NAME, CREATED_BY, UPDATED_BY) values  (UUID(), "VENDOR", USER(), USER());
