/*
 * Drop main tables for FINS MDM Accounts System API
 */

DROP TABLE IF EXISTS CONTACT_POINT_ADDRESS_CONTACT_POINT_TYPE_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_ADDRESS_PARTY_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_ADDRESS;

DROP TABLE IF EXISTS CONTACT_POINT_EMAIL_CONTACT_POINT_TYPE_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_EMAIL_PARTY_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_EMAIL;

DROP TABLE IF EXISTS CONTACT_POINT_PHONE_CONTACT_POINT_TYPE_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_PHONE_PARTY_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_PHONE;

DROP TABLE IF EXISTS CONTACT_POINT_CONTACT_POINT_TYPE_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_PARTY_JOIN;
DROP TABLE IF EXISTS CONTACT_POINT_TYPE;
DROP TABLE IF EXISTS CONTACT_POINT;

DROP TABLE IF EXISTS EXTERNAL_ID_EXTERNAL_ID_TYPE_JOIN;
DROP TABLE IF EXISTS EXTERNAL_ID_PARTY_JOIN;
DROP TABLE IF EXISTS EXTERNAL_ID_PARTY_ROLE_JOIN;
DROP TABLE IF EXISTS EXTERNAL_ID_TYPE;
DROP TABLE IF EXISTS EXTERNAL_ID;

DROP TABLE IF EXISTS PARTY_RELATED_PARTY_RELATED_PARTY_JOIN;
DROP TABLE IF EXISTS PARTY_RELATED_PARTY_PARTY_JOIN;
DROP TABLE IF EXISTS PARTY_RELATED_PARTY;
DROP TABLE IF EXISTS PARTY_RELATIONSHIP_TYPE;

DROP TABLE IF EXISTS CUSTOMER_PARTY_JOIN;
DROP TABLE IF EXISTS PARTY_ROLE_PARTY_JOIN;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PARTY_ROLE;
DROP TABLE IF EXISTS HOUSEHOLD;
DROP TABLE IF EXISTS INDIVIDUAL;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS PARTY;
