{
  "globalParty": "3f337f22-7211-11eb-a776-0e41569acf90",
  "partyType": "Individual",
  "noMergeReason": "et",
  "birthDate": "1994-01-16",
  "birthPlace": "Floridashire",
  "childrenCount": 2,
  "consumerCreditScore": 73548089,
  "consumerCreditScoreProviderName": "Experian",
  "convictionsCount": 53,
  "currentEmployerName": "West - Flatley",
  "deathDate": "2017-10-09",
  "deathPlace": "",
  "dependentCount": 216,
  "doExtractMyDataUpdateDate": "1964-04-13",
  "doForgetMeFromUpdateDate": "2017-10-09",
  "doNotMarketFromUpdateDate": "1993-08-11",
  "doNotProcessFromUpdateDate": "1949-01-15",
  "doNotProcessReason": "nostrud",
  "doNotProfileFromUpdateDate": "1989-03-04",
  "doNotTrackLocationUpdateDate": "1988-05-29",
  "doNotTrackUpdateDate": "1960-11-01",
  "employedSinceDate": "1961-07-03",
  "ethnicity": "American",
  "externalIds": [
    {
      "id": "e0441093-918d-11eb-b4c8-0233bdd64096",
      "externalId": "e044106f-918d-11eb-b4c8-0233bdd64096",
      "externalIdType": [
        "MDM"
      ],
      "status": "VALID",
      "statusLastChangedDate": "2021-03-30T19:26:50.000Z"
    }
  ],
  "firstName": "Anthony",
  "gender": "male",
  "hasAlcoholAbuseHistory": false,
  "hasDrugAbuseHistory": false,
  "highestEducationLevel": "Bachelors of Sciences",
  "hospitalizationsLast5YearsCount": 724001,
  "id": "e044106f-918d-11eb-b4c8-0233bdd64096",
  "influencerRating": 47065285,
  "isAlcoholConsumer": true,
  "isGoodStudent": true,
  "isHighRiskOccupation": false,
  "isTobaccoConsume": false,
  "lastName": "Hermiston",
  "mailingName": "rest",
  "mainDietaryHabitType": "Protein",
  "mainDisabilityType": "None",
  "mainLifeAttitudeType": "high",
  "mainLifeStyleType": "Lavish",
  "mainPersonalityType": "Active",
  "mainPersonalValueType": "Rich",
  "majorCitationCount": 830,
  "maritalStatus": "Single",
  "middleName": "Schaden",
  "militaryService": "None",
  "militaryStatus": "Retired",
  "mothersMaidenName": "VonRueden",
  "nameSuffix": "Mr.",
  "netWorth": 1611975,
  "occupation": "Developer",
  "occupationType": "official",
  "officialName": "Jenks",
  "orderingName": "dolore",
  "personHeight": 96,
  "personLifeStage": "Adult",
  "personName": "Belinda Frami",
  "personWeight": 148,
  "personWeightUnitOfMeasure": "lbs",
  "preferredName": "Cassin",
  "primaryHobby": "fishing",
  "religion": "None",
  "residenceCaptureMethod": "culpa",
  "residenceCountryName": "USA",
  "salutation": "Ms.",
  "secondLastName": "",
  "sendIndividualData": true,
  "shouldForget": true,
  "surgeriesLast5YearsCount": 52,
  "taxBracketRange": "22%",
  "webSiteURL": "ashton.net",
  "weddingAnniversaryDate": "1944-12-10",
  "yearlyIncome": 310634,
  "yearlyIncomeRange": "2000000",
  "auditInfo": {
    "createdBy": "accel-mdm-sys-api-v2-dev",
    "createdDate": "2021-03-30T19:26:50.000Z",
    "updatedBy": "accel-mdm-sys-api-v2-dev",
    "updatedDate": "2021-03-30T19:26:50.000Z",
    "isDeleted": false
  }
}