{
  "inboundAttachmentNames": [],
  "exceptionPayload": null,
  "inboundPropertyNames": [],
  "outboundAttachmentNames": [],
  "outboundPropertyNames": [],
  "payload": [
    "select DISTINCT indv.BIRTH_DATE,indv.BIRTH_PLACE,indv.CHILDREN_COUNT,indv.CONSUMER_CREDIT_SCORE,\nindv.CONSUMER_CREDIT_SCORE_PROVIDER_NAME,indv.CONVICTIONS_COUNT,indv.CREATED_BY,indv.CREATED_DATE,\nindv.CURRENT_EMPLOYER_NAME,indv.DEATH_DATE,indv.DEATH_PLACE,indv.DEPENDENT_COUNT,indv.DO_EXTRACT_MY_DATA_UPDATE_DATE,\nindv.DO_FORGET_ME_FROM_UPDATE_DATE,indv.DO_NOT_MARKET_FROM_UPDATE_DATE,indv.DO_NOT_PROCESS_FROM_UPDATE_DATE,indv.DO_NOT_PROCESS_REASON,\nindv.DO_NOT_PROFILE_FROM_UPDATE_DATE,indv.DO_NOT_TRACK_LOCATION_UPDATE_DATE,indv.DO_NOT_TRACK_UPDATE_DATE,indv.EMPLOYED_SINCE_DATE,\nindv.ETHNICITY,indv.FIRST_NAME,indv.GENDER,indv.GLOBAL_PARTY,indv.HAS_ALCOHOL_ABUSE_HISTORY,indv.HAS_DRUG_ABUSE_HISTORY,\nindv.HIGHEST_EDUCATION_LEVEL,indv.HOSPITALIZATIONS_LAST5_YEARS_COUNT,indv.ID,indv.INFLUENCER_RATING,indv.IS_ALCOHOL_CONSUMER,\nindv.IS_DRUG_CONSUMER,indv.IS_GOOD_DRIVER,indv.IS_GOOD_STUDENT,indv.IS_HIGH_RISK_HOBBY,indv.IS_HIGH_RISK_OCCUPATION,\nindv.IS_HOME_OWNER,indv.IS_TOBACCO_CONSUME,indv.LAST_NAME,indv.MAILING_NAME,indv.MAIN_DIETARY_HABIT_TYPE,\nindv.MAIN_DISABILITY_TYPE,indv.MAIN_LIFE_ATTITUDE_TYPE,indv.MAIN_LIFE_STYLE_TYPE,indv.MAIN_PERSONAL_VALUE_TYPE,\nindv.MAIN_PERSONALITY_TYPE,indv.MAJOR_CITATION_COUNT,indv.MARITAL_STATUS,indv.MIDDLE_NAME,indv.MILITARY_SERVICE,\nindv.MILITARY_STATUS,indv.MINOR_CITATION_COUNT,indv.MOTHERS_MAIDEN_NAME,indv.NAME_SUFFIX,indv.NET_WORTH,\nindv.NO_MERGE_REASON,indv.OCCUPATION,indv.OCCUPATION_TYPE,indv.OFFICIAL_NAME,indv.ORDERING_NAME,\nindv.OVER_AGE_NUMBER,indv.PARTY_TYPE,indv.PERSON_HEIGHT,indv.PERSON_HEIGHT_UNIT_OF_MEASURE,indv.PERSON_LIFE_STAGE,\nindv.PERSON_NAME,indv.PERSON_WEIGHT,indv.PERSON_WEIGHT_UNIT_OF_MEASURE,indv.PHOTO_URL,indv.PREFERRED_NAME,\nindv.PRIMARY_HOBBY,indv.RELIGION,indv.RESIDENCE_CAPTURE_METHOD,indv.RESIDENCE_COUNTRY_NAME,indv.SALUTATION,indv.SECOND_LAST_NAME,\nindv.SEND_INDIVIDUAL_DATA,indv.SHOULD_FORGET,indv.SURGERIES_LAST5_YEARS_COUNT,indv.TAX_BRACKET_RANGE,indv.UPDATED_BY,\nindv.UPDATED_DATE,indv.WEB_SITE_URL,indv.WEDDING_ANNIVERSARY_DATE,indv.YEARLY_INCOME,indv.YEARLY_INCOME_RANGE  from INDIVIDUAL indv,PARTY p where indv.ID=p.ID and p.ID in \n(select DISTINCT eipj.PARTY_ID from EXTERNAL_ID_PARTY_JOIN eipj,EXTERNAL_ID ei,EXTERNAL_ID_TYPE eit \nwhere  ei.id = eipj.EXTERNAL_ID and  eit.ID = ei.EXTERNAL_ID_TYPE and \nei.EXTERNAL_ID= 'INDVBCZXWC21121') limit 10 offset 0",
    "select DISTINCT indv.BIRTH_DATE,indv.BIRTH_PLACE,indv.CHILDREN_COUNT,indv.CONSUMER_CREDIT_SCORE,\nindv.CONSUMER_CREDIT_SCORE_PROVIDER_NAME,indv.CONVICTIONS_COUNT,indv.CREATED_BY,indv.CREATED_DATE,\nindv.CURRENT_EMPLOYER_NAME,indv.DEATH_DATE,indv.DEATH_PLACE,indv.DEPENDENT_COUNT,indv.DO_EXTRACT_MY_DATA_UPDATE_DATE,\nindv.DO_FORGET_ME_FROM_UPDATE_DATE,indv.DO_NOT_MARKET_FROM_UPDATE_DATE,indv.DO_NOT_PROCESS_FROM_UPDATE_DATE,indv.DO_NOT_PROCESS_REASON,\nindv.DO_NOT_PROFILE_FROM_UPDATE_DATE,indv.DO_NOT_TRACK_LOCATION_UPDATE_DATE,indv.DO_NOT_TRACK_UPDATE_DATE,indv.EMPLOYED_SINCE_DATE,\nindv.ETHNICITY,indv.FIRST_NAME,indv.GENDER,indv.GLOBAL_PARTY,indv.HAS_ALCOHOL_ABUSE_HISTORY,indv.HAS_DRUG_ABUSE_HISTORY,\nindv.HIGHEST_EDUCATION_LEVEL,indv.HOSPITALIZATIONS_LAST5_YEARS_COUNT,indv.ID,indv.INFLUENCER_RATING,indv.IS_ALCOHOL_CONSUMER,\nindv.IS_DRUG_CONSUMER,indv.IS_GOOD_DRIVER,indv.IS_GOOD_STUDENT,indv.IS_HIGH_RISK_HOBBY,indv.IS_HIGH_RISK_OCCUPATION,\nindv.IS_HOME_OWNER,indv.IS_TOBACCO_CONSUME,indv.LAST_NAME,indv.MAILING_NAME,indv.MAIN_DIETARY_HABIT_TYPE,\nindv.MAIN_DISABILITY_TYPE,indv.MAIN_LIFE_ATTITUDE_TYPE,indv.MAIN_LIFE_STYLE_TYPE,indv.MAIN_PERSONAL_VALUE_TYPE,\nindv.MAIN_PERSONALITY_TYPE,indv.MAJOR_CITATION_COUNT,indv.MARITAL_STATUS,indv.MIDDLE_NAME,indv.MILITARY_SERVICE,\nindv.MILITARY_STATUS,indv.MINOR_CITATION_COUNT,indv.MOTHERS_MAIDEN_NAME,indv.NAME_SUFFIX,indv.NET_WORTH,\nindv.NO_MERGE_REASON,indv.OCCUPATION,indv.OCCUPATION_TYPE,indv.OFFICIAL_NAME,indv.ORDERING_NAME,\nindv.OVER_AGE_NUMBER,indv.PARTY_TYPE,indv.PERSON_HEIGHT,indv.PERSON_HEIGHT_UNIT_OF_MEASURE,indv.PERSON_LIFE_STAGE,\nindv.PERSON_NAME,indv.PERSON_WEIGHT,indv.PERSON_WEIGHT_UNIT_OF_MEASURE,indv.PHOTO_URL,indv.PREFERRED_NAME,\nindv.PRIMARY_HOBBY,indv.RELIGION,indv.RESIDENCE_CAPTURE_METHOD,indv.RESIDENCE_COUNTRY_NAME,indv.SALUTATION,indv.SECOND_LAST_NAME,\nindv.SEND_INDIVIDUAL_DATA,indv.SHOULD_FORGET,indv.SURGERIES_LAST5_YEARS_COUNT,indv.TAX_BRACKET_RANGE,indv.UPDATED_BY,\nindv.UPDATED_DATE,indv.WEB_SITE_URL,indv.WEDDING_ANNIVERSARY_DATE,indv.YEARLY_INCOME,indv.YEARLY_INCOME_RANGE from INDIVIDUAL indv,PARTY p,CONTACT_POINT_EMAIL cpe, CONTACT_POINT_EMAIL_PARTY_JOIN cpepj \nwhere indv.ID = p.ID and cpepj.PARTY_ID = p.ID and cpe.ID = cpepj.CONTACT_POINT_EMAIL_ID \nand cpe.EMAIL_ADDRESS= 'test1@testsalesforce.com'  limit 10 offset 0"
  ],
  "attributes": {
    "headers": {
      "authorization": "Basic ZTZiMzRkYTdjOTEyNGI4ZDkzOTYzYmRmNzYyMjNlNWI6YzA2MTM3MTdhODZjNDJCRDgwOGNEMkZhRUU1MzYyRDg=",
      "user-agent": "PostmanRuntime/7.26.10",
      "accept": "*/*",
      "host": "localhost:8082",
      "accept-encoding": "gzip, deflate, br",
      "connection": "keep-alive"
    },
    "clientCertificate": null,
    "method": "GET",
    "scheme": "https",
    "queryParams": {
      "offset": "0",
      "limit": "10",
      "emailAddress": "test1@testsalesforce.com",
      "externalId": "INDVBCZXWC21121"
    },
    "requestUri": "/api/individuals?offset=0&limit=10&emailAddress=test1@testsalesforce.com&externalId=INDVBCZXWC21121",
    "queryString": "offset=0&limit=10&emailAddress=test1@testsalesforce.com&externalId=INDVBCZXWC21121",
    "version": "HTTP/1.1",
    "maskedRequestPath": "/individuals",
    "listenerPath": "/api/*",
    "relativePath": "/api/individuals",
    "localAddress": "/127.0.0.1:8082",
    "uriParams": {},
    "rawRequestUri": "/api/individuals?offset=0&limit=10&emailAddress=test1@testsalesforce.com&externalId=INDVBCZXWC21121",
    "rawRequestPath": "/api/individuals",
    "remoteAddress": "/127.0.0.1:54281",
    "requestPath": "/api/individuals"
  }
}