# API specification
api:
  # Replace with respective autodiscovery id
  autodiscoveryID: "00000000"

# Listener configuration
https:
  host: "0.0.0.0"
  port: "8082"

# API configuration
mdm-sys-api:
  http-listener:
    path: "/api/*"

# MDM database connection      
mdm:
  database:
    name: "bfsi_mdm"
    host: "128.199.253.112"
    port: "3306"
    username: "admin"
    password: "NJCLabsMariadb123Bfsi*"
    default-offset: "0"
    default-limit: "50"
    reconnect:
      frequency: "2000"
      attempts: "3"
